'''Simple Generator for fibonacci number
in Fibonacci series new number is generated by adding previous two number first two fibonacci numbers
are 0 and 1.
so fibonacci series
0, 1 , 1 , 2 , 3, 5, 8, 13, 21, 34.......
'''
def sub(limit):
	#initializing first two fibonacci number
	a, b = 0, 1

	#one by one yield next fibonacci number
	while a < limit:
		yield a
		a, b = b, a+b
#Using For in Loop 
print("\n For In Loop \n")
for i in sub(5):
	print(i)
